server:
  port: 10010

spring:
  application:
    name: Coupra-merchant-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.hush.Coupra

knife4j:
  enable: true
  setting:
    language: zh_cn


rocketmq:
  name-server: 127.0.0.1:9876 # NameServer 地址，如果 VM 参数里设置了星球云服务器 RocketMQ 地址，运行时会替换
  producer:
    # 通用生产者组，其中的 ${unique-name:} 是为了避免大家公用一个 Topic，造成你发的消息被其他同学消费，其他同学发的消息被你消费等问题
    group: Coupra_merchant-admin${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数
